apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagesdemo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 8080
        
